project: platform
spec:
  source:
    repoURL: 'https://github.com/empathyco/platform-spark-kubernetes-samples.git'
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
